In [1]:
import pandas as pd
import numpy as np
import seaborn as sns
import matplotlib.pyplot as plt

In [2]:
anime = pd.read_csv("anime.csv")
sys = pd.read_csv("anime_with_synopsis.csv")

In [3]:
anime.head()

,MAL_ID,Name,Score,Genres,English name,Japanese name,Type,Episodes,Aired,Premiered,...,Score-10,Score-9,Score-8,Score-7,Score-6,Score-5,Score-4,Score-3,Score-2,Score-1
0,1,Cowboy Bebop,8.78,"Action, Adventure, Comedy, Drama, Sci-Fi, Space",Cowboy Bebop,カウボーイビバップ,TV,26,"Apr 3, 1998 to Apr 24, 1999",Spring 1998,...,229170.0,182126.0,131625.0,62330.0,20688.0,8904.0,3184.0,1357.0,741.0,1580.0
1,5,Cowboy Bebop: Tengoku no Tobira,8.39,"Action, Drama, Mystery, Sci-Fi, Space",Cowboy Bebop:The Movie,カウボーイビバップ 天国の扉,Movie,1,"Sep 1, 2001",Unknown,...,30043.0,49201.0,49505.0,22632.0,5805.0,1877.0,577.0,221.0,109.0,379.0
2,6,Trigun,8.24,"Action, Sci-Fi, Adventure, Comedy, Drama, Shounen",Trigun,トライガン,TV,26,"Apr 1, 1998 to Sep 30, 1998",Spring 1998,...,50229.0,75651.0,86142.0,49432.0,15376.0,5838.0,1965.0,664.0,316.0,533.0
3,7,Witch Hunter Robin,7.27,"Action, Mystery, Police, Supernatural, Drama, ...",Witch Hunter Robin,Witch Hunter ROBIN (ウイッチハンターロビン),TV,26,"Jul 2, 2002 to Dec 24, 2002",Summer 2002,...,2182.0,4806.0,10128.0,11618.0,5709.0,2920.0,1083.0,353.0,164.0,131.0
4,8,Bouken Ou Beet,6.98,"Adventure, Fantasy, Shounen, Supernatural",Beet the Vandel Buster,冒険王ビィト,TV,52,"Sep 30, 2004 to Sep 29, 2005",Fall 2004,...,312.0,529.0,1242.0,1713.0,1068.0,634.0,265.0,83.0,50.0,27.0

In [4]:
sys.head()

,MAL_ID,Name,Score,Genres,sypnopsis
0,1,Cowboy Bebop,8.78,"Action, Adventure, Comedy, Drama, Sci-Fi, Space","In the year 2071, humanity has colonized sever..."
1,5,Cowboy Bebop: Tengoku no Tobira,8.39,"Action, Drama, Mystery, Sci-Fi, Space","other day, another bounty—such is the life of ..."
2,6,Trigun,8.24,"Action, Sci-Fi, Adventure, Comedy, Drama, Shounen","Vash the Stampede is the man with a $$60,000,0..."
3,7,Witch Hunter Robin,7.27,"Action, Mystery, Police, Supernatural, Drama, ...",ches are individuals with special powers like ...
4,8,Bouken Ou Beet,6.98,"Adventure, Fantasy, Shounen, Supernatural",It is the dark century and the people are suff...

In [5]:
anime = anime.merge(sys,on="MAL_ID")
anime.head()

,MAL_ID,Name_x,Score_x,Genres_x,English name,Japanese name,Type,Episodes,Aired,Premiered,...,Score-6,Score-5,Score-4,Score-3,Score-2,Score-1,Name_y,Score_y,Genres_y,sypnopsis
0,1,Cowboy Bebop,8.78,"Action, Adventure, Comedy, Drama, Sci-Fi, Space",Cowboy Bebop,カウボーイビバップ,TV,26,"Apr 3, 1998 to Apr 24, 1999",Spring 1998,...,20688.0,8904.0,3184.0,1357.0,741.0,1580.0,Cowboy Bebop,8.78,"Action, Adventure, Comedy, Drama, Sci-Fi, Space","In the year 2071, humanity has colonized sever..."
1,5,Cowboy Bebop: Tengoku no Tobira,8.39,"Action, Drama, Mystery, Sci-Fi, Space",Cowboy Bebop:The Movie,カウボーイビバップ 天国の扉,Movie,1,"Sep 1, 2001",Unknown,...,5805.0,1877.0,577.0,221.0,109.0,379.0,Cowboy Bebop: Tengoku no Tobira,8.39,"Action, Drama, Mystery, Sci-Fi, Space","other day, another bounty—such is the life of ..."
2,6,Trigun,8.24,"Action, Sci-Fi, Adventure, Comedy, Drama, Shounen",Trigun,トライガン,TV,26,"Apr 1, 1998 to Sep 30, 1998",Spring 1998,...,15376.0,5838.0,1965.0,664.0,316.0,533.0,Trigun,8.24,"Action, Sci-Fi, Adventure, Comedy, Drama, Shounen","Vash the Stampede is the man with a $$60,000,0..."
3,7,Witch Hunter Robin,7.27,"Action, Mystery, Police, Supernatural, Drama, ...",Witch Hunter Robin,Witch Hunter ROBIN (ウイッチハンターロビン),TV,26,"Jul 2, 2002 to Dec 24, 2002",Summer 2002,...,5709.0,2920.0,1083.0,353.0,164.0,131.0,Witch Hunter Robin,7.27,"Action, Mystery, Police, Supernatural, Drama, ...",ches are individuals with special powers like ...
4,8,Bouken Ou Beet,6.98,"Adventure, Fantasy, Shounen, Supernatural",Beet the Vandel Buster,冒険王ビィト,TV,52,"Sep 30, 2004 to Sep 29, 2005",Fall 2004,...,1068.0,634.0,265.0,83.0,50.0,27.0,Bouken Ou Beet,6.98,"Adventure, Fantasy, Shounen, Supernatural",It is the dark century and the people are suff...

# .1 Columns

In [6]:
# mal_id, name, genres, sypno
anime = anime[["MAL_ID","Name_x","Genres_x","sypnopsis","Score_y"]]
anime.head()

,MAL_ID,Name_x,Genres_x,sypnopsis,Score_y
0,1,Cowboy Bebop,"Action, Adventure, Comedy, Drama, Sci-Fi, Space","In the year 2071, humanity has colonized sever...",8.78
1,5,Cowboy Bebop: Tengoku no Tobira,"Action, Drama, Mystery, Sci-Fi, Space","other day, another bounty—such is the life of ...",8.39
2,6,Trigun,"Action, Sci-Fi, Adventure, Comedy, Drama, Shounen","Vash the Stampede is the man with a $$60,000,0...",8.24
3,7,Witch Hunter Robin,"Action, Mystery, Police, Supernatural, Drama, ...",ches are individuals with special powers like ...,7.27
4,8,Bouken Ou Beet,"Adventure, Fantasy, Shounen, Supernatural",It is the dark century and the people are suff...,6.98

In [7]:
anime["Tag"] = anime.Genres_x +" "+ anime.sypnopsis

In [8]:
anime.head()

,MAL_ID,Name_x,Genres_x,sypnopsis,Score_y,Tag
0,1,Cowboy Bebop,"Action, Adventure, Comedy, Drama, Sci-Fi, Space","In the year 2071, humanity has colonized sever...",8.78,"Action, Adventure, Comedy, Drama, Sci-Fi, Spac..."
1,5,Cowboy Bebop: Tengoku no Tobira,"Action, Drama, Mystery, Sci-Fi, Space","other day, another bounty—such is the life of ...",8.39,"Action, Drama, Mystery, Sci-Fi, Space other da..."
2,6,Trigun,"Action, Sci-Fi, Adventure, Comedy, Drama, Shounen","Vash the Stampede is the man with a $$60,000,0...",8.24,"Action, Sci-Fi, Adventure, Comedy, Drama, Shou..."
3,7,Witch Hunter Robin,"Action, Mystery, Police, Supernatural, Drama, ...",ches are individuals with special powers like ...,7.27,"Action, Mystery, Police, Supernatural, Drama, ..."
4,8,Bouken Ou Beet,"Adventure, Fantasy, Shounen, Supernatural",It is the dark century and the people are suff...,6.98,"Adventure, Fantasy, Shounen, Supernatural It i..."

In [9]:
anime.drop(columns=["Genres_x","sypnopsis"],inplace=True)
anime.head()

,MAL_ID,Name_x,Score_y,Tag
0,1,Cowboy Bebop,8.78,"Action, Adventure, Comedy, Drama, Sci-Fi, Spac..."
1,5,Cowboy Bebop: Tengoku no Tobira,8.39,"Action, Drama, Mystery, Sci-Fi, Space other da..."
2,6,Trigun,8.24,"Action, Sci-Fi, Adventure, Comedy, Drama, Shou..."
3,7,Witch Hunter Robin,7.27,"Action, Mystery, Police, Supernatural, Drama, ..."
4,8,Bouken Ou Beet,6.98,"Adventure, Fantasy, Shounen, Supernatural It i..."

In [10]:
anime.dropna(inplace=True)

In [11]:
anime.Score_y = anime.Score_y.replace({
    "Unknown":np.nan
})
anime.Score_y.fillna(anime.Score_y.median,inplace=True)

In [15]:
from sklearn.feature_extraction.text import TfidfVectorizer
from sklearn.metrics.pairwise import cosine_similarity
import nltk
from nltk.stem.porter import PorterStemmer
nltk.download('stopwords')
from nltk.corpus import stopwords

stemmer = PorterStemmer()
stop_words = set(stopwords.words('english'))
def preprocess(text):
    # Lowercase
    text = text.lower()

    text = ''.join(char for char in text if char.isalnum() or char.isspace())
    
    words = text.split()

    words = [stemmer.stem(word) for word in words if word not in stop_words]
    
    return ' '.join(words)
anime.Tag = anime.Tag.apply(preprocess)    
tfidf = TfidfVectorizer(stop_words='english', max_features=10000)
tfidf_matrix = tfidf.fit_transform(anime['Tag'])

similarity = cosine_similarity(tfidf_matrix)

[nltk_data] Downloading package stopwords to
[nltk_data]     C:\Users\Win\AppData\Roaming\nltk_data...
[nltk_data]   Package stopwords is already up-to-date!

In [16]:
def recommend(anime_name, top_n=5):
    # Find the index of the anime
   
    idx = anime[anime['Name_x'] == anime_name].index[0]
    
    # Get similarity scores for this anime with all others
    distances = similarity[idx]
    
    # Sort by similarity (highest first) and get top_n
    anime_list = sorted(list(enumerate(distances)), reverse=True, key=lambda x: x[1])[1:top_n+1]
    
    # Print recommended anime names
    for i in anime_list:
        print(anime.iloc[i[0]]['Name_x'])

In [28]:
recommend("One Punch Man")

One Punch Man: Road to Hero
Urawa no Usagi-chan
One Punch Man 2nd Season
The Four Seasons
One Punch Man Specials

In [ ]:
import pickle

# Save TF-IDF vectorizer
pickle.dump(tfidf, open("tfidf_vectorizer.pkl", "wb"))

# Save similarity matrix
pickle.dump(similarity, open("similarity_matrix.pkl", "wb"))

# Save cleaned DataFrame
anime.to_pickle("anime_df.pkl")

In [ ]:
import streamlit as st

tfidf = pickle.load(open("tfidf_vectorizer.pkl", "rb"))
similarity = pickle.load(open("similarity_matrix.pkl", "rb"))

# App title
st.title("Anime Recommender System")

# User input
anime_name_input = st.text_input("Enter your favorite anime:")

if st.button("Recommend"):
    anime_name = anime_name_input.replace(" ", "").lower()
    if anime_name in anime['Name_x'].values:
        idx = anime[anime['Name_x'] == anime_name].index[0]
        distances = similarity[idx]
        anime_list = sorted(list(enumerate(distances)), reverse=True, key=lambda x: x[1])[1:6]
        st.write("Top recommendations:")
        for i in anime_list:
            st.write(anime.iloc[i[0]]['name'])
    else:
        st.write("Anime not found. Try another name.")